name: Tag development releases

on:
  push:
    branches:
      - master
      - '[0-9].[0-9].x'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the source code
        uses: actions/checkout@v2

      - name: Push the tag
        run: 'curl -X POST -H "Authorization: token ${{ secrets.PAT }}" -d "{\"ref\": \"refs/tags/$(git rev-parse --abbrev-ref HEAD)-dev\",\"sha\": \"$(git rev-parse HEAD)\"}" https://api.github.com/repos/bartfeenstra/betty/git/refs'
